# Generated by Django 3.2.2 on 2021-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210514_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_by',
            field=models.CharField(default='', max_length=500),
        ),
    ]
